### ISSUE TITLE
WSDL error

### ISSUE THREAD

**Issue by Sipike** [strongloop/strong-soap#27] opened 2016-10-05 07:36 UTC
Something wrong with wsdl parsing. I get this error msgs. Server side.

Element {http://schemas.xmlsoap.org/wsdl/}wsdl:part is not allowed within "wsdl:message"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:part is not allowed within "wsdl:message"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:part is not allowed within "wsdl:message"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:part is not allowed within "wsdl:message"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:part is not allowed within "wsdl:message"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:part is not allowed within "wsdl:message"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:part is not allowed within "wsdl:message"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:part is not allowed within "wsdl:message"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:part is not allowed within "wsdl:message"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:part is not allowed within "wsdl:message"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:operation is not allowed within "wsdl:portType"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:input is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:output is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:operation is not allowed within "wsdl:portType"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:input is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:output is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:operation is not allowed within "wsdl:portType"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:input is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:output is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:operation is not allowed within "wsdl:portType"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:input is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:output is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:operation is not allowed within "wsdl:portType"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:input is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:output is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/soap/}soap:binding is not allowed within "wsdl:binding"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:operation is not allowed within "wsdl:binding"
Element {http://schemas.xmlsoap.org/wsdl/soap/}soap:operation is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:input is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/soap/}soap:body is not allowed within "wsdl:input"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:output is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/soap/}soap:body is not allowed within "wsdl:output"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:operation is not allowed within "wsdl:binding"
Element {http://schemas.xmlsoap.org/wsdl/soap/}soap:operation is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:input is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/soap/}soap:body is not allowed within "wsdl:input"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:output is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/soap/}soap:body is not allowed within "wsdl:output"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:operation is not allowed within "wsdl:binding"
Element {http://schemas.xmlsoap.org/wsdl/soap/}soap:operation is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/}wsdl:input is not allowed within "wsdl:operation"
Element {http://schemas.xmlsoap.org/wsdl/soap/}soap:body is not allowed within "wsdl:input"

**Comment by rashmihunt** [comment] 2016-10-05 22:28
Can you please attach your WSDL?

**Comment by Sipike** [comment] 2016-10-06 07:42
Yes of course. Attached.
[doc.zip](https://github.com/strongloop/strong-soap/files/513110/doc.zip)

**Comment by rashmihunt** [comment] 2016-10-07 15:23
Can you test your usecase again with master? https://github.com/strongloop/strong-soap/issues/20 might have fixed your issue.

**Comment by raymondfeng** [comment] 2016-10-07 15:52
@rashmihunt The warnings @Sipike saw should not happen. #20 only hides the warnings.

**Comment by raymondfeng** [comment] 2016-10-07 15:53
@rashmihunt You can try to load the wsdl from @Sipike using strong-soap to check.

**Comment by rashmihunt** [comment] 2016-10-07 16:09
@raymondfeng I did load @Sipike WSDL yesterday after the #20 and there was no warnings. I do have a todo to check this particular case to make sure debug is not hiding the actual problem. I wanted to unblock @Sipike first.

**Comment by raymondfeng** [comment] 2016-10-07 16:17
I tried to load his WSDL with DEBUG=strong-soap:wsdl:element. No warnings are reported. 

@Sipike Please try too.

**Comment by rashmihunt** [comment] 2016-10-07 17:14
@Sipike I loaded your OCIT-I_PD-SP.wsdl without #20 fix and I don't see the warnings even then.  Is there a test case to reproduce?

**Comment by Sipike** [comment] 2016-10-07 17:43
I will try it again and come back with answer.

**Comment by Sipike** [comment] 2016-10-10 07:47
Okey , now I don't see any error msgs, but client.describe() give me an empty object...

**Comment by rashmihunt** [comment] 2016-10-10 17:09
Did you try modifying one of the examples (e.g weather.js) which is under strong-soap\example or mocha tests which are under strong-soap\test to create the client from your wsdl and see if it works? Those are good resources to try your usecases going forward. Which is what I did and I see the client object is created correctly and client.describe is not null. I copied your 'doc' directory under \strong-soap and modified weather.js to communitytest.js to create the client with your wsdl. I don't see any problem. Copy  communitytest.js under \example and run from an IDE or command line using 'node communitytest.js'. 
[communitytest.js.zip](https://github.com/strongloop/strong-soap/files/520029/communitytest.js.zip)
[Screen Shot 2016-10-10 at 9.49.19 AM.zip](https://github.com/strongloop/strong-soap/files/520028/Screen.Shot.2016-10-10.at.9.49.19.AM.zip)

**Comment by Sipike** [comment] 2016-10-11 08:32
I tried it with your example and it works, but If i create a new project it is not works..
Copied communitytest.js to my project's folder and my client.describe() is empty.
I attached my project can u look at it ? (server and client)
[POC_SOAP_NODE.zip](https://github.com/strongloop/strong-soap/files/521263/POC_SOAP_NODE.zip)

**Comment by rashmihunt** [comment] 2016-10-12 19:41
@Sipike I unzipped your POC_SOAP_NODE.zip into a directory and ran 'npm i' and 'node communitytest.js' commands.  I don't see any problem and I see 'operation name: getContentInfo' printed correctly on the console. Wondering if there is an issue with your environment. I am on node version v6.3.0 and npm version 3.10.3? What version are you using?

**Comment by rashmihunt** [comment] 2016-10-12 20:13
@Sipike I am also looking into ocit_server.js and ocit_server.js

**Comment by rashmihunt** [comment] 2016-10-12 22:37
@Sipike I spent some more time looking at ocit_server.js and there seems to be a problem in strong-soap code in wsdl.js for this case wsdl --> includes XSD --> XSDs. I am labeling this issue as a bug.

**Comment by Sipike** [comment] 2016-10-13 07:18
I'm using node version 4.5.0 and npm is 2.15.9

**Comment by rashmihunt** [comment] 2016-10-27 15:45
@Sipike I looked into this issue some more. From the server side when it loads wsdl --> includes XSD --> XSDs, it needs both path and uri to be passed in as part of pathOrOptions as a second parameter to soap.listen() function. I have modified ocit_server.js with this change. Please take a look. I will plan on spending some more time to look at ocit_client.js sending the  JSON request to this server.
[ocit_server.js.zip](https://github.com/strongloop/strong-soap/files/556353/ocit_server.js.zip)

**Comment by Sipike** [comment] 2016-10-31 10:33
Thanks for your answer :) It's working now.

**Comment by rashmihunt** [comment] 2016-12-07 18:40
Closing since this issue is working for the originator.

**Closed by rashmihunt** 2016-12-07 18:40 UTC
Labels: #tob, bug
