### ISSUE TITLE
WSDL attribute not parsed

### ISSUE THREAD

**Issue by murcialito** [strongloop/strong-soap#43] opened 2016-11-21 17:56 UTC
Attributes are ignored while parsing complexType WSDL element

Explanation from the example in this repo:

If we modify the local WSDL to include an attribute named "facade" in the request GetCityWeatherByZIP 

`<s:element name="GetCityWeatherByZIP">
                <s:complexType>
                    <s:sequence>
                        <s:element minOccurs="0" maxOccurs="1" name="ZIP"
                                   type="s:string"/>
                    </s:sequence>
                    <s:attribute name="facade" fixed="fixedtext" type="string"/>
                </s:complexType>
            </s:element>`

The added attribute will be ignored and nothing will be added to the element in the final request.

The expected output for this modification is something like:

`<s11:Envelope xmlns:s11=\"http: //schemas.xmlsoap.org/soap/envelope/">
  <s11:Body>
    <ns1:GetCityWeatherByZIP xmlns:ns1='http://ws.cdyne.com/WeatherWS/' facade='fixedtext'>
      <ns1:ZIP>?XXX?</ns1:ZIP>
    </ns1:GetCityWeatherByZIP>
  </s11:Body>
</s11:Envelope>`

**Comment by ritch** [comment] 2016-11-29 22:08
Can you post some code that reproduces this against the weather api you are using?

Thanks 😄

**Comment by ritch** [comment] 2016-11-29 22:08
Marking as a bug for now...

**Comment by murcialito** [comment] 2016-12-01 15:49
I used the code in this file below

https://github.com/strongloop/strong-soap/blob/master/example/weather.js

But instead of using the online WSDL I modified the online version to add my attribute

<s:attribute name="facade" fixed="fixedtext" type="string"/>

The attribute is not picked up and is not sent in the request to the exampple Weather Api

Thanks!

**Comment by rashmihunt** [comment] 2017-01-20 23:07
@murcialito  
At the moment, strong-soap doesn’t have support to read ‘fixed’ value defined for the attribute in the schema.  You can open an enhancement request/issue for this. You could also open a PR implementing the same.

Meanwhile, you can achieve the same by adding $attributes in your JSON input.
For e.g in the weather web service use case you mentioned, your JSON request can be 

```
var requestArgs = {  
            ZIP: '94306',  
            "$attributes": {"facade": "fixedtext"} 
};
```

Weather web service has been down lately and you can try it with stockquote service example in strong-soap module. https://github.com/strongloop/strong-soap/blob/master/example/stockquote.js

In this case, your JSON request can be 
```
var requestArgs = {  
   symbol: 'IBM',     
   "$attributes": {"facade": "fixed"}
 };
```
Let me know if this solves your issue.

**Comment by rashmihunt** [comment] 2017-01-25 18:49
@murcialito Let me know if above explanation solves your issue. I would like to close this issue.

**Comment by murcialito** [comment] 2017-01-26 14:10
@rashmihunt It doesn't seem to be working for me, below is the generated output for requestArgs 

```
<ZIP>94306</ZIP>
<$attributes>
   <facade>fixedtext</facade>
</$attributes>
```
I have created a custom HttpClient to add the fixed attribute meanwhile this is supported.
Thanks

**Comment by rashmihunt** [comment] 2017-02-01 23:30
Closing since originator has a workaround and also opened a 'enhancement' issue to support processing 'fixed' value from schema, https://github.com/strongloop/strong-soap/issues/77

**Closed by rashmihunt** 2017-02-01 23:30 UTC
Labels: major, triage
